window.INITIAL_PROGRAMS = [
  {
    "id": "1",
    "programNo": "303",
    "nameAr": "التاريخ",
    "degree": "بكالوريوس",
    "nameEn": "History",
    "college": "كلية الاداب والعلوم الانسانية",
    "department": "التاريخ الاسلامي",
    "programStatus": "مستمر",
    "capacity": "601",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "304",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "2",
    "programNo": "303",
    "nameAr": "التاريخ",
    "degree": "ماجستير",
    "nameEn": "History",
    "college": "كلية الاداب والعلوم الانسانية",
    "department": "التاريخ الاسلامي",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "306",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "3",
    "programNo": "1309",
    "nameAr": "الجغرافية التطبيقية",
    "degree": "بكالوريوس",
    "nameEn": "B.Sc in Applied Geography",
    "college": "كلية الاداب والعلوم الانسانية",
    "department": "الجغرافيا التطبيقية",
    "programStatus": "مستمر",
    "capacity": "173",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "313",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "4",
    "programNo": "301",
    "nameAr": "اللغة العربية وآدابها",
    "degree": "ماجستير",
    "nameEn": "Arabic Language and  Literature",
    "college": "كلية الاداب والعلوم الانسانية",
    "department": "اللغة العربية وآدابها",
    "programStatus": "مستمر",
    "capacity": "66",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "305",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "5",
    "programNo": "301",
    "nameAr": "اللغة العربية وآدابها",
    "degree": "بكالوريوس",
    "nameEn": "B.Sc. in Arabic Language and Literature",
    "college": "كلية الاداب والعلوم الانسانية",
    "department": "اللغة العربية وآدابها",
    "programStatus": "مستمر",
    "capacity": "838",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "6",
    "programNo": "1307",
    "nameAr": "الفلسفه في اللغه العربيه وأدابها",
    "degree": "دكتوراه",
    "nameEn": "PhD in Arabic Language and Literature",
    "college": "كلية الاداب والعلوم الانسانية",
    "department": "اللغة العربية وآدابها",
    "programStatus": "موقوف",
    "capacity": "33",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "311",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "7",
    "programNo": "517",
    "nameAr": "الادارة اللوجستية",
    "degree": "بكالوريوس",
    "nameEn": "Logistics Management",
    "college": "كلية الاعمال",
    "department": "ادارة الأعمال و الادارة العامة",
    "programStatus": "مستمر",
    "capacity": "120",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "319",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "8",
    "programNo": "505",
    "nameAr": "الإدارة  العامة",
    "degree": "ماجستير",
    "nameEn": "Public Administration",
    "college": "كلية الاعمال",
    "department": "ادارة الأعمال و الادارة العامة",
    "programStatus": "موقوف",
    "capacity": "44",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "309",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "9",
    "programNo": "514",
    "nameAr": "التسويق الرقمي",
    "degree": "بكالوريوس",
    "nameEn": "Digital Marketing",
    "college": "كلية الاعمال",
    "department": "ادارة الأعمال و الادارة العامة",
    "programStatus": "مستمر",
    "capacity": "409",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "314",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "10",
    "programNo": "502",
    "nameAr": "إدارة الأعمال",
    "degree": "بكالوريوس",
    "nameEn": "Business Administration",
    "college": "كلية الاعمال",
    "department": "ادارة الأعمال و الادارة العامة",
    "programStatus": "مستمر",
    "capacity": "535",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "11",
    "programNo": "502",
    "nameAr": "إدارة الأعمال",
    "degree": "ماجستير",
    "nameEn": "Business Administration",
    "college": "كلية الاعمال",
    "department": "ادارة الأعمال و الادارة العامة",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "308",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "12",
    "programNo": "507",
    "nameAr": "اقتصاديات المال والأعمال",
    "degree": "ماجستير",
    "nameEn": "Finance and Business Economics",
    "college": "كلية الاعمال",
    "department": "اقتصاد المال والأعمال",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "307",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "13",
    "programNo": "510",
    "nameAr": "الاقتصاد الرقمي",
    "degree": "بكالوريوس",
    "nameEn": "Digital Economy",
    "college": "كلية الاعمال",
    "department": "اقتصاد المال والأعمال",
    "programStatus": "مستمر",
    "capacity": "120",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "316",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "14",
    "programNo": "512",
    "nameAr": "الاقتصاد والتعاون الدولي",
    "degree": "ماجستير",
    "nameEn": "Economic and Multinational Cooperation",
    "college": "كلية الاعمال",
    "department": "اقتصاد المال والأعمال",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "313",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "15",
    "programNo": "518",
    "nameAr": "التدقيق والمحاسبة الدولية",
    "degree": "بكالوريوس",
    "nameEn": "International Accounting and Auditing",
    "college": "كلية الاعمال",
    "department": "التدقيق وقانون الأعمال",
    "programStatus": "مستمر",
    "capacity": "90",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "320",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "16",
    "programNo": "509",
    "nameAr": "المحاسبة وقانون الاعمال",
    "degree": "بكالوريوس",
    "nameEn": "Accountancy and Business Law",
    "college": "كلية الاعمال",
    "department": "التدقيق وقانون الأعمال",
    "programStatus": "مستمر",
    "capacity": "511",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "311",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "17",
    "programNo": "513",
    "nameAr": "الاقتصاد والمصارف الاسلامية",
    "degree": "ماجستير",
    "nameEn": "Islamic Economics and Banking",
    "college": "كلية الاعمال",
    "department": "التمويل والمصارف",
    "programStatus": "مستمر",
    "capacity": "0",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "18",
    "programNo": "516",
    "nameAr": "التكنولوجيا المالية",
    "degree": "بكالوريوس",
    "nameEn": "Financial Technology",
    "college": "كلية الاعمال",
    "department": "التمويل والمصارف",
    "programStatus": "مستمر",
    "capacity": "164",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "317",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "19",
    "programNo": "503",
    "nameAr": "التمويل والمصارف",
    "degree": "بكالوريوس",
    "nameEn": "Banking and Finance",
    "college": "كلية الاعمال",
    "department": "التمويل والمصارف",
    "programStatus": "مستمر",
    "capacity": "598",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "303",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "20",
    "programNo": "503",
    "nameAr": "التمويل والمصارف",
    "degree": "ماجستير",
    "nameEn": "Economics of Finance Business",
    "college": "كلية الاعمال",
    "department": "التمويل والمصارف",
    "programStatus": "موقوف",
    "capacity": "44",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "305",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "21",
    "programNo": "504",
    "nameAr": "المحاسبة",
    "degree": "بكالوريوس",
    "nameEn": "Accounting",
    "college": "كلية الاعمال",
    "department": "المحاسبة",
    "programStatus": "مستمر",
    "capacity": "578",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "22",
    "programNo": "504",
    "nameAr": "المحاسبة",
    "degree": "ماجستير",
    "nameEn": "Accounting",
    "college": "كلية الاعمال",
    "department": "المحاسبة",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "306",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "23",
    "programNo": "515",
    "nameAr": "النظم المحاسبية و تحليل الأعمال",
    "degree": "بكالوريوس",
    "nameEn": "Accounting Systems and Business Analytic",
    "college": "كلية الاعمال",
    "department": "المحاسبة",
    "programStatus": "مستمر",
    "capacity": "120",
    "authorityCollegeNo": "205",
    "authorityProgramNo": "318",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "24",
    "programNo": "908",
    "nameAr": "علم البيانات والذكاء الاصطناعي",
    "degree": "بكالوريوس",
    "nameEn": "Data Science and Artificial Intelligence",
    "college": "كلية الامير الحسين بن عبدالله لتكنولوجيا المعلومات",
    "department": "علم البيانات والذكاء الاصطناعي",
    "programStatus": "مستمر",
    "capacity": "313",
    "authorityCollegeNo": "211",
    "authorityProgramNo": "307",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "25",
    "programNo": "906",
    "nameAr": "الأمن السيبراني",
    "degree": "بكالوريوس",
    "nameEn": "Cyber Security",
    "college": "كلية الامير الحسين بن عبدالله لتكنولوجيا المعلومات",
    "department": "علم الحاسوب",
    "programStatus": "مستمر",
    "capacity": "341",
    "authorityCollegeNo": "211",
    "authorityProgramNo": "306",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "26",
    "programNo": "901",
    "nameAr": "علوم الحاسوب",
    "degree": "بكالوريوس",
    "nameEn": "Computer Science",
    "college": "كلية الامير الحسين بن عبدالله لتكنولوجيا المعلومات",
    "department": "علم الحاسوب",
    "programStatus": "موقوف",
    "capacity": "352",
    "authorityCollegeNo": "211",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "27",
    "programNo": "901",
    "nameAr": "علوم الحاسوب",
    "degree": "ماجستير",
    "nameEn": "Computer Science",
    "college": "كلية الامير الحسين بن عبدالله لتكنولوجيا المعلومات",
    "department": "علم الحاسوب",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "211",
    "authorityProgramNo": "304",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "28",
    "programNo": "907",
    "nameAr": "تطوير تطبيقات الاجهزة الذكية",
    "degree": "بكالوريوس",
    "nameEn": "Smart Device Application Development",
    "college": "كلية الامير الحسين بن عبدالله لتكنولوجيا المعلومات",
    "department": "نظم المعلومات الحاسوبية",
    "programStatus": "مستمر",
    "capacity": "90",
    "authorityCollegeNo": "211",
    "authorityProgramNo": "309",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "29",
    "programNo": "904",
    "nameAr": "نظم المعلومات الادارية",
    "degree": "بكالوريوس",
    "nameEn": "Management Of Information Systems",
    "college": "كلية الامير الحسين بن عبدالله لتكنولوجيا المعلومات",
    "department": "نظم المعلومات الحاسوبية",
    "programStatus": "مستمر",
    "capacity": "464",
    "authorityCollegeNo": "211",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "30",
    "programNo": "909",
    "nameAr": "نظم المعلومات الصحية",
    "degree": "بكالوريوس",
    "nameEn": "Health Information Systems",
    "college": "كلية الامير الحسين بن عبدالله لتكنولوجيا المعلومات",
    "department": "نظم المعلومات الحاسوبية",
    "programStatus": "مستمر",
    "capacity": "86",
    "authorityCollegeNo": "211",
    "authorityProgramNo": "308",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "31",
    "programNo": "902",
    "nameAr": "نظم معلومات حاسوبية",
    "degree": "بكالوريوس",
    "nameEn": "Computer Information Systems",
    "college": "كلية الامير الحسين بن عبدالله لتكنولوجيا المعلومات",
    "department": "نظم المعلومات الحاسوبية",
    "programStatus": "مستمر",
    "capacity": "307",
    "authorityCollegeNo": "211",
    "authorityProgramNo": "303",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "32",
    "programNo": "1001",
    "nameAr": "البكالوريوس في التمريض",
    "degree": "بكالوريوس",
    "nameEn": ". B. Sc.  In Nursing",
    "college": "كلية الاميرة سلمى بنت عبدالله للتمريض",
    "department": "تمريض صحة البالغين",
    "programStatus": "مستمر",
    "capacity": "1074",
    "authorityCollegeNo": "212",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "33",
    "programNo": "1002",
    "nameAr": "تمريض صحة البالغين/ العناية الحثيثة",
    "degree": "ماجستير",
    "nameEn": "Adult Health Nursing/Critical Care",
    "college": "كلية الاميرة سلمى بنت عبدالله للتمريض",
    "department": "تمريض صحة البالغين",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "212",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "34",
    "programNo": "1020",
    "nameAr": "تمريض صحة المجتمع",
    "degree": "ماجستير",
    "nameEn": "Community Health Nursing",
    "college": "كلية الاميرة سلمى بنت عبدالله للتمريض",
    "department": "تمريض صحة البالغين",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "212",
    "authorityProgramNo": "303",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "35",
    "programNo": "1108",
    "nameAr": "التربية البدنية",
    "degree": "بكالوريوس",
    "nameEn": "Physical Education",
    "college": "كلية التربية البدنية وعلوم الرياضة",
    "department": "التربية البدنية",
    "programStatus": "مستمر",
    "capacity": "614",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "315",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "36",
    "programNo": "1901",
    "nameAr": "التربية البدنية",
    "degree": "بكالوريوس",
    "nameEn": "Physical Education",
    "college": "كلية التربية البدنية وعلوم الرياضة",
    "department": "التربية البدنية",
    "programStatus": "مستمر",
    "capacity": "100",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "315",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "37",
    "programNo": "1902",
    "nameAr": "علوم الحركة والرياضة التطبيقية",
    "degree": "بكالوريوس",
    "nameEn": "Applied Sport and Movement Sciences",
    "college": "كلية التربية البدنية وعلوم الرياضة",
    "department": "علوم الحركة والرياضة التطبيقية",
    "programStatus": "مستمر",
    "capacity": "100",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "317",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "38",
    "programNo": "4911",
    "nameAr": "التربية البدنية والصحية",
    "degree": "دبلوم متوسط",
    "nameEn": "Physical and Health Education",
    "college": "كلية التعليم التقني",
    "department": "العلوم الإدارية والإنسانية",
    "programStatus": "مستمر",
    "capacity": "0",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "39",
    "programNo": "4910",
    "nameAr": "إدارة التزويد",
    "degree": "دبلوم متوسط",
    "nameEn": "Supply Management",
    "college": "كلية التعليم التقني",
    "department": "العلوم الإدارية والإنسانية",
    "programStatus": "مستمر",
    "capacity": "0",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "40",
    "programNo": "4930",
    "nameAr": "التمريض المشارك",
    "degree": "دبلوم متوسط",
    "nameEn": "Associate Nursing",
    "college": "كلية التعليم التقني",
    "department": "المهن الطبية",
    "programStatus": "مستمر",
    "capacity": "0",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "41",
    "programNo": "4931",
    "nameAr": "تكنولوجيا الأشعة",
    "degree": "دبلوم متوسط",
    "nameEn": "Radiology Technology",
    "college": "كلية التعليم التقني",
    "department": "المهن الطبية",
    "programStatus": "مستمر",
    "capacity": "0",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "42",
    "programNo": "4920",
    "nameAr": "إنترنت الأشياء",
    "degree": "دبلوم متوسط",
    "nameEn": "Internet of Things",
    "college": "كلية التعليم التقني",
    "department": "الهندسة و الأنظمة الذكية",
    "programStatus": "مستمر",
    "capacity": "0",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "43",
    "programNo": "4926",
    "nameAr": "تكنولوجيا الزراعة الذكية",
    "degree": "دبلوم متوسط",
    "nameEn": "Smart Agriculture Technology",
    "college": "كلية التعليم التقني",
    "department": "الهندسة و الأنظمة الذكية",
    "programStatus": "مستمر",
    "capacity": "0",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "44",
    "programNo": "4923",
    "nameAr": "تكنولوجيا الطاقة",
    "degree": "دبلوم متوسط",
    "nameEn": "Energy Technology",
    "college": "كلية التعليم التقني",
    "department": "الهندسة و الأنظمة الذكية",
    "programStatus": "مستمر",
    "capacity": "0",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "45",
    "programNo": "4921",
    "nameAr": "مساحة الطرق وحساب الكميات",
    "degree": "دبلوم متوسط",
    "nameEn": "Road Surveying and Quantity Surveying",
    "college": "كلية التعليم التقني",
    "department": "الهندسة و الأنظمة الذكية",
    "programStatus": "مستمر",
    "capacity": "0",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "46",
    "programNo": "4922",
    "nameAr": "هندسة الأبنية الذكية",
    "degree": "دبلوم متوسط",
    "nameEn": "Smart Building Engineering",
    "college": "كلية التعليم التقني",
    "department": "الهندسة و الأنظمة الذكية",
    "programStatus": "مستمر",
    "capacity": "0",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "47",
    "programNo": "205",
    "nameAr": "التحكيم في عقود الانشاءات",
    "degree": "ماجستير",
    "nameEn": "Arbitration of Construction Contracts",
    "college": "كلية الحقوق",
    "department": "القانون الخاص",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "204",
    "authorityProgramNo": "304",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "48",
    "programNo": "204",
    "nameAr": "الحقوق",
    "degree": "بكالوريوس",
    "nameEn": "Law",
    "college": "كلية الحقوق",
    "department": "القانون الخاص",
    "programStatus": "مستمر",
    "capacity": "260",
    "authorityCollegeNo": "204",
    "authorityProgramNo": "303",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "49",
    "programNo": "200",
    "nameAr": "القانـــــــــــون",
    "degree": "ماجستير",
    "nameEn": "Law",
    "college": "كلية الحقوق",
    "department": "القانون الخاص",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "204",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "50",
    "programNo": "104",
    "nameAr": "الفقه واصوله",
    "degree": "بكالوريوس",
    "nameEn": "Islamic Jurisprudence(Fiqh Wa Usuluh)",
    "college": "كلية الشريعة",
    "department": "الفقة واصوله",
    "programStatus": "مستمر",
    "capacity": "512",
    "authorityCollegeNo": "201",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "51",
    "programNo": "104",
    "nameAr": "الفقه وأصوله",
    "degree": "ماجستير",
    "nameEn": "Islamic Jurisprudence",
    "college": "كلية الشريعة",
    "department": "الفقة واصوله",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "201",
    "authorityProgramNo": "304",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "52",
    "programNo": "108",
    "nameAr": "الفلسفة في الفقه وأصوله",
    "degree": "دكتوراه",
    "nameEn": "Doctorate of Philosophy in Fiqh WaUsuluh",
    "college": "كلية الشريعة",
    "department": "الفقة واصوله",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "201",
    "authorityProgramNo": "308",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "53",
    "programNo": "106",
    "nameAr": "القضاء الشرعي",
    "degree": "ماجستير",
    "nameEn": "Legislative Law",
    "college": "كلية الشريعة",
    "department": "الفقة واصوله",
    "programStatus": "مستمر",
    "capacity": "66",
    "authorityCollegeNo": "201",
    "authorityProgramNo": "305",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "54",
    "programNo": "105",
    "nameAr": "اصول الدين",
    "degree": "بكالوريوس",
    "nameEn": "Foundations of Islam (Usul addin)",
    "college": "كلية الشريعة",
    "department": "أصول الدين",
    "programStatus": "مستمر",
    "capacity": "258",
    "authorityCollegeNo": "201",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "55",
    "programNo": "105",
    "nameAr": "أصول الدين",
    "degree": "ماجستير",
    "nameEn": "Islamic Creed (Aqeeda)",
    "college": "كلية الشريعة",
    "department": "أصول الدين",
    "programStatus": "مستمر",
    "capacity": "66",
    "authorityCollegeNo": "201",
    "authorityProgramNo": "303",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "56",
    "programNo": "109",
    "nameAr": "دراسات في الاديان",
    "degree": "بكالوريوس",
    "nameEn": "Religious Studies",
    "college": "كلية الشريعة",
    "department": "دراسات في الأديان",
    "programStatus": "مستمر",
    "capacity": "170",
    "authorityCollegeNo": "201",
    "authorityProgramNo": "309",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "57",
    "programNo": "401",
    "nameAr": "الرياضيات",
    "degree": "بكالوريوس",
    "nameEn": "math 401",
    "college": "كلية العلوم",
    "department": "الرياضيات",
    "programStatus": "مستمر",
    "capacity": "546",
    "authorityCollegeNo": "207",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "58",
    "programNo": "401",
    "nameAr": "الرياضيات",
    "degree": "ماجستير",
    "nameEn": "Mathematics",
    "college": "كلية العلوم",
    "department": "الرياضيات",
    "programStatus": "مستمر",
    "capacity": "66",
    "authorityCollegeNo": "207",
    "authorityProgramNo": "305",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "59",
    "programNo": "404",
    "nameAr": "العلوم الحياتية",
    "degree": "بكالوريوس",
    "nameEn": "math 411",
    "college": "كلية العلوم",
    "department": "العلوم الحياتية",
    "programStatus": "مستمر",
    "capacity": "363",
    "authorityCollegeNo": "207",
    "authorityProgramNo": "304",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "60",
    "programNo": "404",
    "nameAr": "العلوم الحياتية",
    "degree": "ماجستير",
    "nameEn": "Biological Sciences",
    "college": "كلية العلوم",
    "department": "العلوم الحياتية",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "207",
    "authorityProgramNo": "308",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "61",
    "programNo": "402",
    "nameAr": "الفيزياء",
    "degree": "بكالوريوس",
    "nameEn": "Physics",
    "college": "كلية العلوم",
    "department": "الفيزياء",
    "programStatus": "مستمر",
    "capacity": "395",
    "authorityCollegeNo": "207",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "62",
    "programNo": "402",
    "nameAr": "الفيزياء",
    "degree": "ماجستير",
    "nameEn": "Physics",
    "college": "كلية العلوم",
    "department": "الفيزياء",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "207",
    "authorityProgramNo": "306",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "63",
    "programNo": "403",
    "nameAr": "الكيمياء",
    "degree": "بكالوريوس",
    "nameEn": "Chemistry (403)",
    "college": "كلية العلوم",
    "department": "الكيمياء",
    "programStatus": "مستمر",
    "capacity": "383",
    "authorityCollegeNo": "207",
    "authorityProgramNo": "303",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "64",
    "programNo": "403",
    "nameAr": "الكيمياء",
    "degree": "ماجستير",
    "nameEn": "Chemistry",
    "college": "كلية العلوم",
    "department": "الكيمياء",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "207",
    "authorityProgramNo": "307",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "65",
    "programNo": "1106",
    "nameAr": "الادارة التربوية",
    "degree": "ماجستير",
    "nameEn": "Educational Administration",
    "college": "كلية العلوم التربوية",
    "department": "الادارة التربوية",
    "programStatus": "مستمر",
    "capacity": "100",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "309",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "66",
    "programNo": "1107",
    "nameAr": "الإدارة المدرسية",
    "degree": "دبلوم",
    "nameEn": "School Adminstration",
    "college": "كلية العلوم التربوية",
    "department": "الادارة التربوية",
    "programStatus": "مستمر",
    "capacity": "100",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "308",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "67",
    "programNo": "1113",
    "nameAr": "التربية الخاصة",
    "degree": "بكالوريوس",
    "nameEn": "Educational Sciences/Special Education",
    "college": "كلية العلوم التربوية",
    "department": "العلوم النفسية والتربية الخاصة",
    "programStatus": "مستمر",
    "capacity": "755",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "314",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "68",
    "programNo": "1164",
    "nameAr": "تربية طفل",
    "degree": "بكالوريوس",
    "nameEn": "Educational Sciences / Child Eduation",
    "college": "كلية العلوم التربوية",
    "department": "العلوم النفسية والتربية الخاصة",
    "programStatus": "موقوف",
    "capacity": "299",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "69",
    "programNo": "1103",
    "nameAr": "دبلوم صعوبات التعلم",
    "degree": "دبلوم",
    "nameEn": "Diploma in Learning Disabilities",
    "college": "كلية العلوم التربوية",
    "department": "العلوم النفسية والتربية الخاصة",
    "programStatus": "موقوف دائم",
    "capacity": "44",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "313",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "70",
    "programNo": "1401",
    "nameAr": "مناهج التربية الاسلامية واساليب",
    "degree": "ماجستير",
    "nameEn": "Islamic Education Curriculum & its Instr",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "موقوف دائم",
    "capacity": "44",
    "authorityCollegeNo": "0",
    "authorityProgramNo": "0",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "71",
    "programNo": "1165",
    "nameAr": "المناهج والتدريس / الدراسات الاجتماعية",
    "degree": "ماجستير",
    "nameEn": "",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "موقوف",
    "capacity": "44",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "307",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "72",
    "programNo": "1145",
    "nameAr": "المناهج والتدريس / الرياضيات",
    "degree": "ماجستير",
    "nameEn": "",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "304",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "73",
    "programNo": "1155",
    "nameAr": "المناهج والتدريس / العلوم",
    "degree": "ماجستير",
    "nameEn": "",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "303",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "74",
    "programNo": "1115",
    "nameAr": "المناهج والتدريس / اللغة العربية",
    "degree": "ماجستير",
    "nameEn": "",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "305",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "75",
    "programNo": "1175",
    "nameAr": "المناهج والتدريس / المناهج العام",
    "degree": "ماجستير",
    "nameEn": "",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "مستمر",
    "capacity": "88",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "310",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "76",
    "programNo": "1135",
    "nameAr": "المناهج والتدريس/اللغة الانجليزية",
    "degree": "ماجستير",
    "nameEn": "Curricula and Instruction/ English",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "مستمر",
    "capacity": "66",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "306",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "77",
    "programNo": "1105",
    "nameAr": "تكنولوجيا المعلومات والاتصالات ف",
    "degree": "ماجستير",
    "nameEn": "aaa",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "موقوف",
    "capacity": "33",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "316",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "78",
    "programNo": "1104",
    "nameAr": "دبلوم التربية",
    "degree": "دبلوم",
    "nameEn": "Education",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "موقوف دائم",
    "capacity": "88",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "312",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "79",
    "programNo": "1134",
    "nameAr": "معلم صف",
    "degree": "بكالوريوس",
    "nameEn": "Educational Sciences / Classroom Teacher",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "مستمر",
    "capacity": "834",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "80",
    "programNo": "1195",
    "nameAr": "مناهج التربية الاسلامية وأساليب",
    "degree": "ماجستير",
    "nameEn": "Islamic Education Curriculum & its Instr",
    "college": "كلية العلوم التربوية",
    "department": "المناهج والتدريس",
    "programStatus": "موقوف دائم",
    "capacity": "0",
    "authorityCollegeNo": "208",
    "authorityProgramNo": "311",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "81",
    "programNo": "1801",
    "nameAr": "العلوم الطبية المخبرية",
    "degree": "بكالوريوس",
    "nameEn": "Medical Laboratory Science",
    "college": "كلية العلوم الطبية التطبيقية",
    "department": "التحاليل الطبية",
    "programStatus": "مستمر",
    "capacity": "435",
    "authorityCollegeNo": "214",
    "authorityProgramNo": "304",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "82",
    "programNo": "1801",
    "nameAr": "العلوم الطبية المخبرية",
    "degree": "ماجستير",
    "nameEn": "mas of Medical Laboratory Science",
    "college": "كلية العلوم الطبية التطبيقية",
    "department": "التحاليل الطبية",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "214",
    "authorityProgramNo": "309",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "83",
    "programNo": "1802",
    "nameAr": "التغذية السريرية والحميات",
    "degree": "بكالوريوس",
    "nameEn": "Clinical Nutrition and Dietetics",
    "college": "كلية العلوم الطبية التطبيقية",
    "department": "التغذية والحميات",
    "programStatus": "مستمر",
    "capacity": "95",
    "authorityCollegeNo": "214",
    "authorityProgramNo": "307",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "84",
    "programNo": "1807",
    "nameAr": "العلاج التنفسي",
    "degree": "بكالوريوس",
    "nameEn": "Respiratory Therapy",
    "college": "كلية العلوم الطبية التطبيقية",
    "department": "العلوم الطبية المساندة",
    "programStatus": "مستمر",
    "capacity": "110",
    "authorityCollegeNo": "214",
    "authorityProgramNo": "306",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "85",
    "programNo": "1806",
    "nameAr": "تقنيات الأشعة الطبية",
    "degree": "بكالوريوس",
    "nameEn": "Medical Radiologic Technologist",
    "college": "كلية العلوم الطبية التطبيقية",
    "department": "العلوم الطبية المساندة",
    "programStatus": "مستمر",
    "capacity": "149",
    "authorityCollegeNo": "214",
    "authorityProgramNo": "303",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "86",
    "programNo": "1803",
    "nameAr": "العلاج الطبيعي",
    "degree": "بكالوريوس",
    "nameEn": "Physiotherapy",
    "college": "كلية العلوم الطبية التطبيقية",
    "department": "علوم التأهيل",
    "programStatus": "مستمر",
    "capacity": "86",
    "authorityCollegeNo": "214",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "87",
    "programNo": "1804",
    "nameAr": "العلاج الوظيفي",
    "degree": "بكالوريوس",
    "nameEn": "Occupational Therapy",
    "college": "كلية العلوم الطبية التطبيقية",
    "department": "علوم التأهيل",
    "programStatus": "مستمر",
    "capacity": "91",
    "authorityCollegeNo": "214",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "88",
    "programNo": "1805",
    "nameAr": "علوم السمع والنطق",
    "degree": "بكالوريوس",
    "nameEn": "Hearing and Speech Sciences",
    "college": "كلية العلوم الطبية التطبيقية",
    "department": "علوم التأهيل",
    "programStatus": "مستمر",
    "capacity": "129",
    "authorityCollegeNo": "214",
    "authorityProgramNo": "305",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "89",
    "programNo": "1705",
    "nameAr": "اللغة والأدب/اسباني_انجليزي",
    "degree": "بكالوريوس",
    "nameEn": "Language and Literature/Spanish_English",
    "college": "كلية اللغات الأجنبية",
    "department": "اللغة الاسبانية",
    "programStatus": "مستمر",
    "capacity": "609",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "309",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "90",
    "programNo": "1717",
    "nameAr": "اللغة الانجليزية / الادب والنقد",
    "degree": "ماجستير",
    "nameEn": "Master English language and Literature",
    "college": "كلية اللغات الأجنبية",
    "department": "اللغة الانجليزية وآدابها",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "307",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "91",
    "programNo": "1727",
    "nameAr": "اللغة الانجليزية / اللغويات",
    "degree": "ماجستير",
    "nameEn": "Master English language Linguistics",
    "college": "كلية اللغات الأجنبية",
    "department": "اللغة الانجليزية وآدابها",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "308",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "92",
    "programNo": "1702",
    "nameAr": "اللغة الانجليزية وآدابها",
    "degree": "بكالوريوس",
    "nameEn": "English language and Literature",
    "college": "كلية اللغات الأجنبية",
    "department": "اللغة الانجليزية وآدابها",
    "programStatus": "مستمر",
    "capacity": "1001",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "93",
    "programNo": "1706",
    "nameAr": "اللغة والأدب/ايطالي_انجليزي",
    "degree": "بكالوريوس",
    "nameEn": "Language and Literature/Italian_Enlish",
    "college": "كلية اللغات الأجنبية",
    "department": "اللغة الايطالية",
    "programStatus": "مستمر",
    "capacity": "429",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "310",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "94",
    "programNo": "1708",
    "nameAr": "اللغة والأدب/فرنسي_انجليزي",
    "degree": "بكالوريوس",
    "nameEn": "Language and Literature/French_English",
    "college": "كلية اللغات الأجنبية",
    "department": "اللغة الفرنسية",
    "programStatus": "مستمر",
    "capacity": "680",
    "authorityCollegeNo": "206",
    "authorityProgramNo": "312",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "95",
    "programNo": "707",
    "nameAr": "الهندسة الصناعية",
    "degree": "بكالوريوس",
    "nameEn": "Industrial Engineering",
    "college": "كلية الهندسة",
    "department": "الهندسة الصناعية",
    "programStatus": "مستمر",
    "capacity": "85",
    "authorityCollegeNo": "203",
    "authorityProgramNo": "306",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "96",
    "programNo": "704",
    "nameAr": "الهندسة المدنية",
    "degree": "بكالوريوس",
    "nameEn": "Civil Engineering",
    "college": "كلية الهندسة",
    "department": "الهندسة المدنية",
    "programStatus": "مستمر",
    "capacity": "487",
    "authorityCollegeNo": "203",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "97",
    "programNo": "709",
    "nameAr": "هندسة المياه والبيئة والمعلوماتي",
    "degree": "ماجستير",
    "nameEn": "Hydro_Environmental Informatics Engineer",
    "college": "كلية الهندسة",
    "department": "الهندسة المدنية",
    "programStatus": "موقوف دائم",
    "capacity": "33",
    "authorityCollegeNo": "203",
    "authorityProgramNo": "307",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "98",
    "programNo": "706",
    "nameAr": "الطاقة المتجددة والمستدامة",
    "degree": "بكالوريوس",
    "nameEn": "B.Sc.In Renewable and Sustainable Energy",
    "college": "كلية الهندسة",
    "department": "هندسة الطاقة المتجددة",
    "programStatus": "مستمر",
    "capacity": "274",
    "authorityCollegeNo": "203",
    "authorityProgramNo": "304",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "99",
    "programNo": "703",
    "nameAr": "هندسة العمارة",
    "degree": "بكالوريوس",
    "nameEn": "Architectural Engineering",
    "college": "كلية الهندسة",
    "department": "هندسة العمارة والفنون الاسلامية",
    "programStatus": "مستمر",
    "capacity": "308",
    "authorityCollegeNo": "203",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "100",
    "programNo": "703",
    "nameAr": "هندسة العمارة",
    "degree": "ماجستير",
    "nameEn": "Architectural Engineering",
    "college": "كلية الهندسة",
    "department": "هندسة العمارة والفنون الاسلامية",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "203",
    "authorityProgramNo": "305",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "101",
    "programNo": "705",
    "nameAr": "هندسة المساحة",
    "degree": "بكالوريوس",
    "nameEn": "Surveying Engineering",
    "college": "كلية الهندسة",
    "department": "هندسة المساحة",
    "programStatus": "مستمر",
    "capacity": "173",
    "authorityCollegeNo": "203",
    "authorityProgramNo": "303",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "102",
    "programNo": "600",
    "nameAr": "العلوم السياسية",
    "degree": "ماجستير",
    "nameEn": "Political Sciences",
    "college": "كلية بيت الحكمة للعلوم السياسية والدراسات الدولية",
    "department": "معهد بيت الحكمة",
    "programStatus": "مستمر",
    "capacity": "44",
    "authorityCollegeNo": "210",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "103",
    "programNo": "604",
    "nameAr": "العلوم السياسية",
    "degree": "بكالوريوس",
    "nameEn": "Political Sciences",
    "college": "كلية بيت الحكمة للعلوم السياسية والدراسات الدولية",
    "department": "معهد بيت الحكمة",
    "programStatus": "مستمر",
    "capacity": "365",
    "authorityCollegeNo": "210",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "104",
    "programNo": "808",
    "nameAr": "الاقتصاد الازرق والاستدامة البيئية",
    "degree": "ماجستير",
    "nameEn": "Blue Economy and Environmental Sustainab",
    "college": "كلية علوم الارض والبيئة",
    "department": "علوم الارض والبيئة",
    "programStatus": "مستمر",
    "capacity": "33",
    "authorityCollegeNo": "202",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "105",
    "programNo": "806",
    "nameAr": "الجيولوجيا التطبيقية",
    "degree": "ماجستير",
    "nameEn": "aaaa",
    "college": "كلية علوم الارض والبيئة",
    "department": "علوم الارض والبيئة",
    "programStatus": "موقوف",
    "capacity": "33",
    "authorityCollegeNo": "202",
    "authorityProgramNo": "303",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "106",
    "programNo": "803",
    "nameAr": "علوم الارض والبيئة التطبيقية",
    "degree": "بكالوريوس",
    "nameEn": "Applid Geology & Environmental Science",
    "college": "كلية علوم الارض والبيئة",
    "department": "علوم الارض والبيئة",
    "programStatus": "مستمر",
    "capacity": "210",
    "authorityCollegeNo": "202",
    "authorityProgramNo": "301",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "107",
    "programNo": "803",
    "nameAr": "علوم الارض والبيئة التطبيقية",
    "degree": "ماجستير",
    "nameEn": "Applid Geology & Environmental Science",
    "college": "كلية علوم الارض والبيئة",
    "department": "علوم الارض والبيئة",
    "programStatus": "موقوف دائم",
    "capacity": "33",
    "authorityCollegeNo": "202",
    "authorityProgramNo": "302",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "108",
    "programNo": "802",
    "nameAr": "علوم المعلومات الجغرافية",
    "degree": "ماجستير",
    "nameEn": "Geographic Information Sciences",
    "college": "كلية علوم الارض والبيئة",
    "department": "نظم المعلومات الجغرافية",
    "programStatus": "موقوف",
    "capacity": "33",
    "authorityCollegeNo": "202",
    "authorityProgramNo": "305",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  },
  {
    "id": "109",
    "programNo": "807",
    "nameAr": "نظم المعلومات الجغرافية والاستشعارعن بعد",
    "degree": "بكالوريوس",
    "nameEn": "Geographical Information Systems",
    "college": "كلية علوم الارض والبيئة",
    "department": "نظم المعلومات الجغرافية",
    "programStatus": "مستمر",
    "capacity": "143",
    "authorityCollegeNo": "202",
    "authorityProgramNo": "304",
    "nqfStatus": "لم يبدأ",
    "nqfReviewResult": "لا يوجد",
    "nqfReceivedDate": "",
    "nqfReviewedDate": "",
    "nqfSentDate": "",
    "accreditationStatus": "لم يبدأ",
    "accreditationReviewResult": "لا يوجد",
    "accreditationReceivedDate": "",
    "accreditationReviewedDate": "",
    "accreditationSentDate": "",
    "owner": "",
    "priority": "متوسطة",
    "notes": "",
    "updatedAt": ""
  }
];
